# This file was generated by GoReleaser. DO NOT EDIT.
cask "obsidian-headless" do
  version "0.3.6"

  on_macos do
    on_intel do
      sha256 "ae2d8b3c2a8a1905d8bb0536b45b4f1ca4b4610f10ab7bd9833a5a382af8cb36"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d76b1528d85cc6d328ea636fa8c2f3f62e0a758dfbc20215477d83eb9bb820eb"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce737d28c1ba7d601c1aaf057c97f94af69a27af6d95e1ae4742354b97b06215"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4004ef94e8d3a7dd8adccbfa697aaa5eab93bae9a91b630d91de9bf3e054c2c2"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Linux_arm64.tar.gz"
    end
  end

  name "obsidian-headless"
  desc "Headless Go client for Obsidian Sync and Publish.
"
  homepage "https://belphemur.github.io/obsidian-headless/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obsidian-headless"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ob"]
    end
  end
  generate_completions_from_executable "obsidian-headless",
    shell_parameter_format: :cobra

  # No zap stanza required

end
