# This file was generated by GoReleaser. DO NOT EDIT.
cask "obsidian-headless" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "85ef6d3fc5e36bc92eb4bc2af4efc94a381a712e2ccae795282e6b7ab98f8a55"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9839a558035127f9c2fa68d95169a113375b7976d80608baccc28ebe5db01f6d"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c5252cae84b7b815216ed0f51e199b60a2bd2c5d7a1944c92b51b1511c22a1d6"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f71af84ddacf71839dabb926d39378a6557e32f60dd54a022554a2cfae8c30c1"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Linux_arm64.tar.gz"
    end
  end

  name "obsidian-headless"
  desc "Headless Go client for Obsidian Sync and Publish.
"
  homepage "https://belphemur.github.io/obsidian-headless/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obsidian-headless"
  generate_completions_from_executable "obsidian-headless",
    shell_parameter_format: :cobra

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ob"]
    end
  end

  # No zap stanza required

end
