# This file was generated by GoReleaser. DO NOT EDIT.
cask "obsidian-headless" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "055dfb0313701a6370c8a861fddc89b4522e8afc7f06a475b9baa284cfb2407c"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "31c8f1c29395926fb47f10cc95c0b2c8a52c09a9b9bb44777ac23049ee7f2a89"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2391ac9bd281deb59dd84572e1d40b1d22bd7406ee597fc9430686c7d6bad079"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2fb260f36ad96323487dc366fc3a34fd7f50a491fab75864bbf7f46b6946583f"
      url "https://github.com/Belphemur/obsidian-headless/releases/download/v#{version}/obsidian-headless_Linux_arm64.tar.gz"
    end
  end

  name "obsidian-headless"
  desc "Headless Go client for Obsidian Sync and Publish.
"
  homepage "https://belphemur.github.io/obsidian-headless/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obsidian-headless"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ob"]
    end
  end
  generate_completions_from_executable "obsidian-headless",
    shell_parameter_format: :cobra

  # No zap stanza required

end
